@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AddAssignmentCommandParser" as AddAssignmentCommandParser LOGIC_COLOR
participant "d:AddAssignmentCommand" as AddAssignmentCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("give 2...")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("give 2...")
activate AddressBookParser

create AddAssignmentCommandParser
AddressBookParser -> AddAssignmentCommandParser
activate AddAssignmentCommandParser

AddAssignmentCommandParser --> AddressBookParser
deactivate AddAssignmentCommandParser

AddressBookParser -> AddAssignmentCommandParser : parse("2 d/... by/...")
activate AddAssignmentCommandParser

create AddAssignmentCommand
AddAssignmentCommandParser -> AddAssignmentCommand
activate AddAssignmentCommand

AddAssignmentCommand --> AddAssignmentCommandParser : r
deactivate AddAssignmentCommand

AddAssignmentCommandParser --> AddressBookParser : r
deactivate AddAssignmentCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
AddAssignmentCommandParser -[hidden]-> AddressBookParser
destroy AddAssignmentCommandParser

AddressBookParser --> LogicManager : r
deactivate AddressBookParser

LogicManager -> AddAssignmentCommand : execute()
activate AddAssignmentCommand

AddAssignmentCommand -> Model : addAssignment(...)
activate Model

Model --> AddAssignmentCommand
deactivate Model

create CommandResult
AddAssignmentCommand -> CommandResult
activate CommandResult

CommandResult --> AddAssignmentCommand
deactivate CommandResult

AddAssignmentCommand --> LogicManager : result
deactivate AddAssignmentCommand

[<--LogicManager
deactivate LogicManager
@enduml
