@startuml
start
:User adds an assignment to a specific person;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([person assignment list does not
contain assignment])
    :Add the new assignment into
            the assignment list;
    :Sort assignment based on
                    due date;
else ([else])
    :Show duplicate assignment
                error message;
endif
stop
@enduml
