@startuml
start
:User wants to find a specific person
with **name** "vishnu" and **module** "CS1101S";

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([no one is named **"vishnu"**
**or** has a **module** of "CS1101S"])
    : Display no one;

else ([else])
    : Display all people with name "vishnu" or module "CS1101S"
                                which matches either criteria;
endif
stop
@enduml
