@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class VersionedAddressBook
Class ReadOnlyAddressBook
Class AddressBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Class UniquePersonList
Class UniqueAssignmentList
Class Person
Class Email
Class Name
Class Tag
Class Assignment
Class Description
Class Status
Class DueDate

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.--|> ReadOnlyAddressBook
VersionedAddressBook -left-|> AddressBook
VersionedAddressBook -left----> "1..~*" ReadOnlyAddressBook: manages state >

ModelManager .up.-|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" VersionedAddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.-|> ReadOnlyUserPrefs

AddressBook *----> "    1" UniqueAssignmentList
AddressBook *---> "1" UniquePersonList
AddressBook -> "active 0..1" Person
AddressBook -> "1" Person: stores filtered list predicate about >

Person *--> " 1" UniqueAssignmentList
Person *--> "1" Name
Person *--> "1 " Email
Person *--> "*" Tag

UniquePersonList -down-> "all~*" Person

UniqueAssignmentList ---> "~*" Assignment: contains >
Assignment *-down-> "1" Description
Assignment *-down-> "1" Status
Assignment *-down-> "1" DueDate
Assignment .down.|> Comparable
Status .down.|> Comparable
DueDate .down.|> Comparable

ModelManager ---->"~* filtered" Person
ModelManager --->"~* observed" Assignment: observes >

UserPrefs -[hidden]down-|>Person

UniqueAssignmentList -[hidden]right-|> Name
AddressBook -[hidden]left-|>ReadOnlyAddressBook
@enduml
