@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class AddressBook
Class ReadOnlyAddressBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs


Class UniquePersonList
Class UniqueAssignmentList
Class Person
Class Email
Class Name
Class Tag
Class Assignment
Class Description
Class Status
Class DueDate
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniqueAssignmentList
UniqueAssignmentList --> "~* " Assignment: contains >
AddressBook *--> "1" UniquePersonList
UniquePersonList ----> "~* all" Person
AddressBook -> "0..1 active " Person

Person *--> "1" UniqueAssignmentList
Person *--> "1" Name
Person *--> "1 " Email
Person *--> "*" Tag

Assignment *-down-> "1" Description
Assignment *-down-> "1" Status
Assignment *-down-> "1" DueDate
Assignment .down.|> Comparable
Status .down.|> Comparable
DueDate .down.|> Comparable



ModelManager -->" ~* filtered" Person
@enduml
