@startuml
start
:User executes removeall command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([persons in module completed
assignment present])
    :Get persons in module;
    :Filter out those who
    completed assignment;
    :Delete assignment
    for filtered persons;
else ([else])
    :Show corresponding
          error message;
endif
stop
@enduml
