@startuml
start
:User executes remove command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([person with required name in current contact list])
    :Get person in module;
    if () then ([person has specified assignment])
        :Delete assignment
        for person;
    else ([else])
        :Show assignment not exist error message;
endif

else ([else])
        :Show person not exist
              error message;
endif
stop
@enduml
