@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class HelpWindow
Class ResultDisplay
Class PersonListPanel
Class PersonCard
Class StatusBarFooter
Class CommandBox
Class AssignmentListPanel
Class AssignmentCard
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
MainWindow *-down->  "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" PersonListPanel
MainWindow *-down-> "1" StatusBarFooter
MainWindow *-down-> "1" AssignmentListPanel
MainWindow --> "0..1" HelpWindow
AssignmentListPanel --|> UiPart
AssignmentCard -|> UiPart


PersonListPanel -down--> "*" PersonCard
AssignmentListPanel ---down> "*" AssignmentCard

MainWindow -left-|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
PersonListPanel ---|> UiPart
PersonCard --|> UiPart
StatusBarFooter -|> UiPart
HelpWindow ---|> UiPart

PersonCard ..> Model
AssignmentCard ..> Model
UiManager -right-> Logic
MainWindow -left-> Logic

PersonListPanel -[hidden]left- HelpWindow
HelpWindow -[hidden]left- CommandBox
CommandBox -[hidden]left- ResultDisplay
ResultDisplay -[hidden]left- StatusBarFooter
PersonListPanel -[hidden]right- AssignmentListPanel


MainWindow -[hidden]down-|> UiPart
CommandBox -[hidden]down-|> UiPart
@enduml
